<?php

return  [
    ['id' =>  1, 'governorate_name' => 'القاهرة', 'governorate_name_en' => 'Cairo'],
    ['id' =>  2, 'governorate_name' => 'الجيزة', 'governorate_name_en' => 'Giza'],
    ['id' =>  3, 'governorate_name' => 'الأسكندرية', 'governorate_name_en' =>  'Alexandria'],
    ['id' =>  4, 'governorate_name' => 'الدقهلية', 'governorate_name_en' => 'Dakahlia'],
    ['id' =>  5, 'governorate_name' => 'البحر الأحمر', 'governorate_name_en' =>  'Red Sea'],
    ['id' =>  6, 'governorate_name' => 'البحيرة', 'governorate_name_en' => 'Beheira'],
    ['id' =>  7, 'governorate_name' => 'الفيوم', 'governorate_name_en' => 'Fayoum'],
    ['id' =>  8, 'governorate_name' => 'الغربية', 'governorate_name_en' => 'Gharbiya'],
    ['id' =>  9, 'governorate_name' => 'الإسماعلية', 'governorate_name_en' =>  'Ismailia'],
    ['id' => 10, 'governorate_name' => 'المنوفية', 'governorate_name_en' => 'Monofia'],
    ['id' => 11, 'governorate_name' => 'المنيا', 'governorate_name_en' => 'Minya'],
    ['id' => 12, 'governorate_name' => 'القليوبية', 'governorate_name_en' => 'Qaliubiya'],
    ['id' => 13, 'governorate_name' => 'الوادي الجديد', 'governorate_name_en' => 'New Valley'],
    ['id' => 14, 'governorate_name' => 'السويس', 'governorate_name_en' => 'Suez'],
    ['id' => 15, 'governorate_name' => 'اسوان', 'governorate_name_en' => 'Aswan'],
    ['id' => 16, 'governorate_name' => 'اسيوط', 'governorate_name_en' => 'Assiut'],
    ['id' => 17, 'governorate_name' => 'بني سويف', 'governorate_name_en' => 'Beni Suef'],
    ['id' => 18, 'governorate_name' => 'بورسعيد', 'governorate_name_en' => 'Port Said'],
    ['id' => 19, 'governorate_name' => 'دمياط', 'governorate_name_en' => 'Damietta'],
    ['id' => 20, 'governorate_name' => 'الشرقية', 'governorate_name_en' => 'Sharkia'],
    ['id' => 21, 'governorate_name' => 'جنوب سيناء', 'governorate_name_en' => 'South Sinai'],
    ['id' => 22, 'governorate_name' => 'كفر الشيخ', 'governorate_name_en' => 'Kafr Al sheikh'],
    ['id' => 23, 'governorate_name' => 'مطروح', 'governorate_name_en' => 'Matrouh'],
    ['id' => 24, 'governorate_name' => 'الأقصر', 'governorate_name_en' =>  'Luxor'],
    ['id' => 25, 'governorate_name' => 'قنا', 'governorate_name_en' => 'Qena'],
    ['id' => 26, 'governorate_name' => 'شمال سيناء', 'governorate_name_en' => 'North Sinai'],
    ['id' => 27, 'governorate_name' => 'سوهاج', 'governorate_name_en' => 'Sohag']
];