<script src="{{asset('front/assets/scripts/libs/jquery-2.1.1.min.js')}}"></script>
<script src="{{asset('front/assets/scripts/libs/jquery-migrate-1.2.1.js@1436763125319')}}"></script>
<script src="{{asset('front/assets/scripts/libs/modernizr.custom.js@1436763125319')}}"></script>
<script src="{{asset('front/assets/plugins/bootstrap/js/bootstrap-rtl.js')}}"></script>
<script src="{{asset('front/assets/plugins/owl-carousel/owl.carousel.min.js')}}"></script>
<script src="{{asset('front/assets/plugins/isotope/jquery.isotope.min.js')}}"></script>
<script src="{{asset('front/assets/scripts/libs/waypoints.min.js')}}"></script>
<script src="{{asset('front/assets/plugins/prettyphoto/js/jquery.prettyPhoto.js')}}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="{{asset('front/assets/plugins/datetimepicker/jquery.datetimepicker.js')}}"></script>
<script src="{{asset('front/assets/plugins/jelect/jquery.jelect.js')}}"></script>
<script src="{{asset('front/assets/plugins/nouislider/jquery.nouislider.all.min.js')}}"></script>
<!-- Loader-->
<script src="{{asset('front/assets/plugins/loader/js/classie.js')}}"></script>
<script src="{{asset('front/assets/plugins/loader/js/pathLoader.js')}}"></script>
<script src="{{asset('front/assets/plugins/loader/js/main.js')}}"></script>
<script src="{{asset('front/assets/scripts/libs/classie.js')}}"></script>
<!-- THEME-->
<script src="{{asset('front/assets/scripts/libs/cssua.min.js')}}"></script>
<script src="{{asset('front/assets/scripts/libs/wow.min.js')}}"></script>
<script src="{{asset('front/assets/scripts/common.js@1436763125319')}}"></script>
<script src="{{asset('front/assets/plugins/rendro-easy-pie-chart/dist/jquery.easypiechart.min.js')}}"></script>